### ISSUE TITLE
problem finding modules

### ISSUE THREAD

**Issue by AndreaQ7** [Sydney-Informatics-Hub/Shotgun-Metagenomics-Analysis#32]
Hello everyone :)
I am trying to use this workflow but when I come to the remove_host_run_parallel.pbs I come to the following error 

ERROR: Unable to locate a modulefile for 'openmpi/4.0.2'
ERROR: Unable to locate a modulefile for 'nci-parallel/1.0.0a'
ERROR: Unable to locate a modulefile for 'bbtools/37.98'

Can you maybe add a short description about how to fix it and in case what is needed to be installed thank you

**Comment by calizilla** [comment]
Hi Andrea, are you executing this workflow on NCI Gadi HPC? The included scripts are written specifically for NCI Gadi, however can be adapted to run on other platforms by adjusting the wrapper scripts. 

The nci-parallel/1.0.0.a module is a wrapper script for OpenMPI written by NCI specifically for Gadi which runs PBS Pro. So unless you are on Gadi, you will need to change the way the parallelisation of tasks across compute is achieved on your infrastructure. If you are on Gadi and this module is not available, please contact NCI helpdesk as `module load nci-parallel/1.0.0a` should work. It now auto-loads `openmpi/4.1.0` the module for openmpi/4.0.2 is no longer required. 

For BBTools, there is no global app installed on Gadi for this but you can [install the latest version](https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/installation-guide/) into your home or other suitable directory, and update the scripts that use this tool to ensure they can access your local installation.
