### ISSUE TITLE
assemble_make_input.sh

### ISSUE THREAD

**Issue by ozge81** [Sydney-Informatics-Hub/Shotgun-Metagenomics-Analysis#33]
Hi,
I try to run assemble but I could not solve this problem
ozge@Lenovo-PC:~$ qsub ./Scripts/assemble_run_parallel.pbs
perl: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host
perl: error: fetch_config: DNS SRV lookup failed
perl: error: _establish_config_source: failed to fetch config
perl: fatal: Could not establish a configuration source

**Comment by calizilla** [comment]
Hi, what compute platform are you running this workflow on? The scritps are set up to run on NCI Gadi HPC and will require modifications to run on a different platform.

**Comment by ozge81** [comment]
> Hi, what compute platform are you running this workflow on? The scritps are set up to run on NCI Gadi HPC and will require modifications to run on a different platform.

Hi, yes I noticed later.. I applied to NCI, thank you
